"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, Download, FileText, Image as ImageIcon, Palette, RotateCcw } from "lucide-react";
import { supabase } from "../../../../lib/supabase";

type Tradie={id:string;full_name:string|null;business_name:string|null;trade:string|null;phone:string|null;email:string|null;slug:string|null;profile_photo_url:string|null;service_area:string|null;about_business:string|null};
const palettes=[
{name:"Vekio Blue",bg:"#071b31",accent:"#70f0ff",ink:"#ffffff",soft:"#d7f7ff"},
{name:"Electric",bg:"#101318",accent:"#ffd84d",ink:"#ffffff",soft:"#f4f4f4"},
{name:"Clean",bg:"#f5f7fa",accent:"#1565c0",ink:"#101828",soft:"#475467"},
{name:"Trade Red",bg:"#241014",accent:"#ff665e",ink:"#ffffff",soft:"#ffe1df"}];
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]||c));}

export default function FlyerDesigner(){
 const {id}=useParams<{id:string}>(); const [t,setT]=useState<Tradie|null>(null); const [loading,setLoading]=useState(true);
 const [business,setBusiness]=useState(""); const [person,setPerson]=useState(""); const [trade,setTrade]=useState(""); const [phone,setPhone]=useState(""); const [email,setEmail]=useState(""); const [area,setArea]=useState(""); const [headline,setHeadline]=useState("Need a reliable local tradie?"); const [offer,setOffer]=useState("Fast, professional service. Scan to view my Vekio profile and send an enquiry."); const [cta,setCta]=useState("SCAN TO VIEW MY VEKIO PROFILE"); const [palette,setPalette]=useState(0); const [showImage,setShowImage]=useState(true); const [generating,setGenerating]=useState(false);
 useEffect(()=>{(async()=>{const {data}=await supabase.from("tradies").select("id,full_name,business_name,trade,phone,email,slug,profile_photo_url,service_area,about_business").eq("slug",id).single(); if(data){setT(data);setBusiness(data.business_name||data.full_name||"My Business");setPerson(data.full_name||"");setTrade(data.trade||"Local trade professional");setPhone(data.phone||"");setEmail(data.email||"");setArea(data.service_area||"");if(data.about_business)setOffer(data.about_business)} setLoading(false)})()},[id]);
 const p=palettes[palette]; const profileUrl=useMemo(()=>`https://www.vekio.com.au/tradie/${t?.slug||id}`,[t,id]); const qrUrl=useMemo(()=>`https://api.qrserver.com/v1/create-qr-code/?size=500x500&margin=8&data=${encodeURIComponent(profileUrl)}`,[profileUrl]);
 function reset(){if(!t)return;setBusiness(t.business_name||t.full_name||"My Business");setPerson(t.full_name||"");setTrade(t.trade||"Local trade professional");setPhone(t.phone||"");setEmail(t.email||"");setArea(t.service_area||"");setHeadline("Need a reliable local tradie?");setOffer(t.about_business||"Fast, professional service. Scan to view my Vekio profile and send an enquiry.");setCta("SCAN TO VIEW MY VEKIO PROFILE");setPalette(0);setShowImage(true)}
 async function dataUrl(url:string){try{const r=await fetch(url);const b=await r.blob();return await new Promise<string>(ok=>{const f=new FileReader();f.onload=()=>ok(String(f.result||""));f.onerror=()=>ok("");f.readAsDataURL(b)})}catch{return""}}
 function save(svg:string,name:string){const b=new Blob([svg],{type:"image/svg+xml"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function download(){setGenerating(true);try{const [qr,photo]=await Promise.all([dataUrl(qrUrl),showImage&&t?.profile_photo_url?dataUrl(t.profile_photo_url):Promise.resolve("")]);if(!qr){alert("QR code could not be generated.");return}const W=1748,H=2480,base=(business||"vekio").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase();const image=photo?`<defs><clipPath id="photo"><rect x="118" y="970" width="560" height="560" rx="55"/></clipPath></defs><image href="${photo}" x="118" y="970" width="560" height="560" preserveAspectRatio="xMidYMid slice" clip-path="url(#photo)"/><rect x="118" y="970" width="560" height="560" rx="55" fill="none" stroke="${p.accent}" stroke-width="8"/>`:"";const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="${p.bg}"/><rect x="70" y="70" width="1608" height="2340" rx="38" fill="none" stroke="${p.accent}" stroke-width="7" opacity=".45"/><text x="118" y="190" fill="${p.accent}" font-family="Arial" font-size="42" font-weight="800" letter-spacing="5">VEKIO PROFESSIONAL</text><text x="118" y="390" fill="${p.ink}" font-family="Arial" font-size="112" font-weight="900">${esc(business.slice(0,28))}</text><text x="118" y="485" fill="${p.soft}" font-family="Arial" font-size="55">${esc(trade.slice(0,44))}</text><text x="118" y="700" fill="${p.ink}" font-family="Arial" font-size="94" font-weight="900">${esc(headline.slice(0,31))}</text><foreignObject x="118" y="770" width="1450" height="180"><div xmlns="http://www.w3.org/1999/xhtml" style="font:40px Arial;color:${p.soft};line-height:1.35">${esc(offer.slice(0,180))}</div></foreignObject>${image}<text x="${photo?740:118}" y="1100" fill="${p.ink}" font-family="Arial" font-size="50" font-weight="800">${esc(person)}</text><text x="${photo?740:118}" y="1190" fill="${p.accent}" font-family="Arial" font-size="72" font-weight="900">${esc(phone)}</text><text x="${photo?740:118}" y="1260" fill="${p.soft}" font-family="Arial" font-size="36">${esc(email)}</text><text x="${photo?740:118}" y="1340" fill="${p.soft}" font-family="Arial" font-size="32">${esc(area.slice(0,60))}</text><rect x="118" y="1690" width="440" height="440" rx="35" fill="#fff"/><image href="${qr}" x="140" y="1712" width="396" height="396"/><text x="620" y="1810" fill="${p.accent}" font-family="Arial" font-size="38" font-weight="900">${esc(cta.slice(0,38))}</text><text x="620" y="1900" fill="${p.ink}" font-family="Arial" font-size="48" font-weight="800">View profile. Check details.</text><text x="620" y="1970" fill="${p.ink}" font-family="Arial" font-size="48" font-weight="800">Send an enquiry directly.</text><text x="620" y="2090" fill="${p.soft}" font-family="Arial" font-size="28">${esc(profileUrl)}</text><text x="118" y="2290" fill="${p.accent}" font-family="Arial" font-size="34" font-weight="800">Powered by Vekio</text></svg>`;save(svg,`${base}-a5-flyer.svg`)}finally{setGenerating(false)}}
 if(loading)return <main className="page-shell print-loading">Loading Print.Vekio…</main>; if(!t)return <main className="page-shell print-loading">Vekio profile not found.</main>;
 return <main className="page-shell print-page"><nav className="nav"><Link className="logo" href={`/print/${id}`}><span className="logo-mark">V</span><span>Print.Vekio</span></Link><Link className="btn btn-secondary" href={`/print/${id}`}><ArrowLeft size={17}/> Products</Link></nav>
 <section className="print-head"><div><div className="eyebrow">Flyers · V1 designer</div><h1>Put your Vekio ID on the street.</h1><p>A simple A5 flyer with your business, direct contact details and unique Vekio QR.</p></div><div className="print-status"><Check size={18}/> Vekio profile connected</div></section>
 <section className="print-workspace"><aside className="card print-controls"><div className="control-title"><FileText size={20}/><strong>Flyer details</strong></div>
 {[["Business name",business,setBusiness,28],["Contact person",person,setPerson,32],["Trade / tagline",trade,setTrade,44],["Phone",phone,setPhone,24],["Email",email,setEmail,50],["Service area",area,setArea,72],["Headline",headline,setHeadline,31],["Message",offer,setOffer,180],["QR call-to-action",cta,setCta,38]].map(([l,v,set,m]:any)=><label key={l}>{l}<input value={v} maxLength={m} onChange={e=>set(e.target.value)}/></label>)}
 {t.profile_photo_url&&<label className="print-image-toggle"><span><ImageIcon size={18}/><span><strong>Profile image</strong><small>Imported automatically from Vekio</small></span></span><input type="checkbox" checked={showImage} onChange={e=>setShowImage(e.target.checked)}/></label>}
 <div className="control-title"><Palette size={20}/><strong>Style</strong></div><div className="palette-picks">{palettes.map((x,i)=><button key={x.name} title={x.name} className={palette===i?"active":""} style={{background:x.bg,borderColor:x.accent}} onClick={()=>setPalette(i)}><span style={{background:x.accent}}/></button>)}</div><button className="btn btn-secondary btn-wide" onClick={reset}><RotateCcw size={17}/> Reset from Vekio</button></aside>
 <section className="print-stage flyer-stage"><div className="stage-label">LIVE PREVIEW · A5 PORTRAIT CONCEPT SIZE</div><div className="flyer-preview" style={{background:p.bg,color:p.ink,borderColor:p.accent}}><div className="flyer-kicker" style={{color:p.accent}}>VEKIO PROFESSIONAL</div><h2>{business}</h2><div className="flyer-trade">{trade}</div><h3>{headline}</h3><p>{offer}</p><div className="flyer-mid">{showImage&&t.profile_photo_url&&<img src={t.profile_photo_url} alt="Profile"/>}<div><b>{person}</b><strong style={{color:p.accent}}>{phone}</strong><span>{email}</span><small>{area}</small></div></div><div className="flyer-bottom"><div className="qr-live"><img src={qrUrl} alt="Vekio QR"/></div><div><b style={{color:p.accent}}>{cta}</b><strong>View profile. Check details.<br/>Send an enquiry directly.</strong><small>{profileUrl}</small></div></div><em style={{color:p.accent}}>Powered by Vekio</em></div>
 <div className="production-note"><strong>A5 Flyer V1.</strong> Generates a single portrait SVG at A5 concept ratio. Final printer bleed, crop marks and PDF preflight come with fulfilment integration.</div><div className="stage-actions"><button className="btn btn-primary" onClick={download} disabled={generating}><Download size={18}/> {generating?"Building artwork…":"Generate A5 flyer SVG"}</button><button className="btn btn-secondary" disabled>Send to print — next</button></div></section></section></main>
}